name: C/C++ CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: melodic
    - name: test
      run: catkin_make
