name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thankyou for creating your first issue for the udp_com ROS package! Our team will review your issue soon and see what we can do to help.'' first issue'
        pr-message: 'Thankyou for creating your first PR! Contributions like yours are exactly why we love open source. Our team will review your proposed changes and get back to you shortly.'' first pr'
